AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation Stack to deploy BCI BigData Enviroment
Resources:
    EMRClusterV5:
        Type: AWS::EMR::Cluster
        Properties:
            Instances:
                MasterInstanceGroup:
                    InstanceCount: 1
                    InstanceType: "m4.large"
                    Market: "ON_DEMAND"
                    Name: "prd-Emr-master-BigData"
                CoreInstanceGroup:
                    InstanceCount: 1
                    InstanceType: "m4.large"
                    Market: "ON_DEMAND"
                    Name: "prd-Emr-core-BigData-Dev"
                Ec2SubnetId:
                    subnet-030c9359
                Ec2KeyName: prd-emr-deploy
                EmrManagedMasterSecurityGroup:
                    sg-00e04cdca1d595f6f
                EmrManagedSlaveSecurityGroup:
                    sg-0a1d5136eb27cb4fe
            BootstrapActions:
                -
                    Name: "BootstrapEMR"
                    ScriptBootstrapAction:
                        Path: "s3://prd-emr-deploy/deploy/boot.sh"
            LogUri: "s3://prd-emr-deploy/logs/"
            Configurations:
            - Classification: hadoop-env
              Configurations:
              - Classification: export
                ConfigurationProperties:
                  JAVA_HOME: "/usr/lib/jvm/java-1.8.0"
            - Classification: spark-env
              Configurations:
              - Classification: export
                ConfigurationProperties:
                  JAVA_HOME: "/usr/lib/jvm/java-1.8.0"
            - Classification: hadoop-log4j
              ConfigurationProperties:
                    hadoop.log.maxfilesize: 256MB
                    hadoop.log.maxbackupindex: '3'
                    hadoop.security.log.maxfilesize: 256MB
                    hadoop.security.log.maxbackupindex: '3'
                    hdfs.audit.log.maxfilesize: 256MB
                    hdfs.audit.log.maxbackupindex: '3'
                    mapred.audit.log.maxfilesize: 256MB
                    mapred.audit.log.maxbackupindex: '3'
                    hadoop.mapreduce.jobsummary.log.maxfilesize: 256MB
                    hadoop.mapreduce.jobsummary.log.maxbackupindex: '3'
            - Classification: hbase-log4j
              ConfigurationProperties:
                  hbase.log.maxbackupindex: '3'
                  hbase.log.maxfilesize: 10MB
                  hbase.security.log.maxbackupindex: '3'
                  hbase.security.log.maxfilesize: 10MB
            - Classification: yarn-site
              ConfigurationProperties:
                  yarn.log-aggregation.retain-seconds: '43200'
            Applications:
            - Name: Hadoop
            - Name: Hive
            - Name: Pig
            - Name: Spark
            - Name: Oozie
            - Name: Zeppelin
            Name: "Emr-cluster-BigData"
            JobFlowRole: "EMR_EC2_DefaultRole"
            ServiceRole: "EMR_DefaultRole"
            ReleaseLabel: "emr-5.17.0"
            VisibleToAllUsers: true
            Tags:
            - Key: Name
              Value:
                Fn::Join:
                - ''
                - - emr-instance-
                  - Ref: AWS::StackName
                  - ''
            - Key: Environment
            - Key: Stack ID
              Value:
                Ref: AWS::StackName
